#! /bin/bash

source /usr/lib/naylib

# sync firefox profiles
draw_heading "Sync firefox profiles"
cd $HOME/.mozilla/firefox/ 
for profile in `grep path -i profiles.ini | sed 's/Path=//g'` ; do
  echo "  $profile"
  cp -r custom_config/*  $profile
done
