#! /bin/bash

source /usr/lib/naylib

# install vim plug pluggins
draw_heading "Sync vim pluggins"

draw_spinner "nvim" "gitsyncer "$HOME/.config/nvim" "git@github.com:Federico-Ciuffardi/nvim_config.git"" || exit 1
