#! /bin/bash

source /usr/lib/naylib

# install zsh plug pluggins
if [ -d ~/.zinit ] && [ -n "$ZSH_VERSION" ]; then
  draw_heading "Sync zsh plugins"
  zsh -c "source ~/.zshrc; zinit self-update; zinit update"
fi
